CREATE TABLE Address
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address       VARCHAR(255),
    number        VARCHAR(255),
    complement    VARCHAR(255),
    neightborhood VARCHAR(255),
    state         VARCHAR(255),
    city          VARCHAR(255),
    observation   VARCHAR(255),
    isMain        BOOLEAN                                 NOT NULL,
    client_id     BIGINT,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE Allergy
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    observation VARCHAR(255),
    patient_id  BIGINT,
    CONSTRAINT pk_allergy PRIMARY KEY (id)
);

CREATE TABLE Client
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    cpf            VARCHAR(255),
    email          VARCHAR(255),
    password       VARCHAR(255),
    birth_date     date,
    sex            VARCHAR(255),
    marital_status VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE Disease
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    symptoms    VARCHAR(255),
    observation VARCHAR(255),
    CONSTRAINT pk_disease PRIMARY KEY (id)
);

CREATE TABLE Medicine
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    VARCHAR(255),
    concentration  INTEGER,
    type           VARCHAR(255),
    stock_quantity INTEGER,
    CONSTRAINT pk_medicine PRIMARY KEY (id)
);

CREATE TABLE MedicineApplication
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                  date,
    hour                  TIME WITHOUT TIME ZONE,
    isApplied             BOOLEAN                                 NOT NULL,
    observation           VARCHAR(255),
    treatment_medicine_id BIGINT,
    CONSTRAINT pk_medicineapplication PRIMARY KEY (id)
);

CREATE TABLE Patient
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    cpf            VARCHAR(255),
    birth_date     date,
    sex            VARCHAR(255),
    marital_status VARCHAR(255),
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

CREATE TABLE Phone
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ddd        VARCHAR(255),
    number     VARCHAR(255),
    is_main    BOOLEAN                                 NOT NULL,
    phone_type VARCHAR(255),
    client_id  BIGINT,
    CONSTRAINT pk_phone PRIMARY KEY (id)
);

CREATE TABLE Privilege
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_privilege PRIMARY KEY (id)
);

CREATE TABLE Role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE Treatment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    begin_date date,
    end_date   date,
    CONSTRAINT pk_treatment PRIMARY KEY (id)
);

CREATE TABLE TreatmentMedicine
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dosage           INTEGER,
    begin_date       date,
    end_date         date,
    begin_hour       TIME WITHOUT TIME ZONE,
    minutes_interval INTEGER,
    treatment_id     BIGINT,
    medicine_id      BIGINT,
    CONSTRAINT pk_treatmentmedicine PRIMARY KEY (id)
);

CREATE TABLE clients_roles
(
    client_id BIGINT NOT NULL,
    role_id   BIGINT NOT NULL
);

CREATE TABLE roles_privileges
(
    privilege_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL
);

CREATE TABLE treatments_diseases
(
    disease_id   BIGINT NOT NULL,
    treatment_id BIGINT NOT NULL
);

ALTER TABLE Address
    ADD CONSTRAINT FK_ADDRESS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES Client (id);

ALTER TABLE Allergy
    ADD CONSTRAINT FK_ALLERGY_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES Patient (id);

ALTER TABLE MedicineApplication
    ADD CONSTRAINT FK_MEDICINEAPPLICATION_ON_TREATMENT_MEDICINE FOREIGN KEY (treatment_medicine_id) REFERENCES TreatmentMedicine (id);

ALTER TABLE Phone
    ADD CONSTRAINT FK_PHONE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES Client (id);

ALTER TABLE TreatmentMedicine
    ADD CONSTRAINT FK_TREATMENTMEDICINE_ON_MEDICINE FOREIGN KEY (medicine_id) REFERENCES Medicine (id);

ALTER TABLE TreatmentMedicine
    ADD CONSTRAINT FK_TREATMENTMEDICINE_ON_TREATMENT FOREIGN KEY (treatment_id) REFERENCES Treatment (id);

ALTER TABLE clients_roles
    ADD CONSTRAINT fk_clirol_on_client FOREIGN KEY (client_id) REFERENCES Client (id);

ALTER TABLE clients_roles
    ADD CONSTRAINT fk_clirol_on_role FOREIGN KEY (role_id) REFERENCES Role (id);

ALTER TABLE roles_privileges
    ADD CONSTRAINT fk_rolpri_on_privilege FOREIGN KEY (privilege_id) REFERENCES Privilege (id);

ALTER TABLE roles_privileges
    ADD CONSTRAINT fk_rolpri_on_role FOREIGN KEY (role_id) REFERENCES Role (id);

ALTER TABLE treatments_diseases
    ADD CONSTRAINT fk_tredis_on_disease FOREIGN KEY (disease_id) REFERENCES Disease (id);

ALTER TABLE treatments_diseases
    ADD CONSTRAINT fk_tredis_on_treatment FOREIGN KEY (treatment_id) REFERENCES Treatment (id);
