name: CICD

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache dependencies with maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Create postgres test database
        run: docker run --name postgres -e POSTGRES_USERNAME=postgres POSTGRES_PASSWORD=postgres POSTGRES_DB=laridosos-test -d -p 5433:5432 postgres

      - name: Execute unit tests
        run: mvn -B test
